apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: bhanukafd/restaurant
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: ClusterIP
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
